---
abstract: 'JSON::XS Data Serializer'
author:
  - 'Nour Sharabash <amirite@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::More: '0'
  perl: '5.006'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Serializer-JSON-XS
no_index:
  directory:
    - t
  package:
    - DB
provides:
  Data::Serializer::JSON::XS:
    file: lib/Data/Serializer/JSON/XS.pm
    version: '0.01'
requires:
  Data::Serializer: '0'
  JSON::XS: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/sharabash/data-serializer-json-xs/issues
  homepage: https://metacpan.org/release/Data-Serializer-JSON-XS
  repository: git://github.com/sharabash/data-serializer-json-xs.git
version: '0.01'
x_authority: cpan:AMIRITE
x_contributors:
  - 'Nour Sharabash <nour.sharabash@gmail.com>'
